// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLb0UpFvYKo0WmEKTqOVXaoT1n5j_yEss',
    appId: '1:987381351843:web:c91707976137e59f8a8616',
    messagingSenderId: '987381351843',
    projectId: 'iot-database-fb343',
    authDomain: 'iot-database-fb343.firebaseapp.com',
    databaseURL: 'https://iot-database-fb343-default-rtdb.firebaseio.com',
    storageBucket: 'iot-database-fb343.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsu6lv9kK6boOicH16xRBwq-Ej_2ajrC4',
    appId: '1:987381351843:android:a8cdd1e2d8af35a88a8616',
    messagingSenderId: '987381351843',
    projectId: 'iot-database-fb343',
    databaseURL: 'https://iot-database-fb343-default-rtdb.firebaseio.com',
    storageBucket: 'iot-database-fb343.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgYMAFNAiN6fvu9Gr89enPMWEcxH6pfAE',
    appId: '1:987381351843:ios:84e91a18c8dfd5918a8616',
    messagingSenderId: '987381351843',
    projectId: 'iot-database-fb343',
    databaseURL: 'https://iot-database-fb343-default-rtdb.firebaseio.com',
    storageBucket: 'iot-database-fb343.appspot.com',
    iosClientId: '987381351843-ldtfdefehp5ko1mh9dpi18hbasfjofcq.apps.googleusercontent.com',
    iosBundleId: 'transportpredictapp.com.example.transportPredictApp',
  );
}
